"""empty message

Revision ID: 660a5ad292e3
Revises: 847cc600da5d
Create Date: 2017-03-19 13:49:22.110802

"""

# revision identifiers, used by Alembic.
revision = '660a5ad292e3'
down_revision = '847cc600da5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphite_group_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphite_group_key_service_id'), 'graphite_group_key', ['service_id'], unique=False)
    op.create_table('graphite_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_graphite_keys_status'), 'graphite_keys', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graphite_keys_status'), table_name='graphite_keys')
    op.drop_table('graphite_keys')
    op.drop_index(op.f('ix_graphite_group_key_service_id'), table_name='graphite_group_key')
    op.drop_table('graphite_group_key')
    ### end Alembic commands ###
